### ISSUE TITLE
"GC overhead limit exceeded" in minimum cut sets fault tree generation

### ISSUE THREAD

**Issue by pbalsgaard** [osate/ErrorModelV2#132]
When generating the minimal cut sets fault tree for a large model, I get several "GC overhead limit exceeded" errors. It makes the basic fault tree and transformed tree for the same model with no error. It also makes the minimal cut sets tree for a smaller model with no error. I'm using the 2.2.2.v20170413-0012 version of EMV2.

The "GC overhead limit exceeded" message shows up with the following errors:
- Unhandled event loop exception
- Periodic workspace save
- Workbench Auto-Save Background Job
- Workbench Auto-Save Job

**Comment by reteprelief** [comment]
By default Eclipse allocates a given amount of heap memory - see osate.ini or eclipse.ini in the folder where Osate is installed. You can change that to a larger number. See for example https://docs.oseems.com/general/application/eclipse/fix-gc-overhead-limit-exceeded
I will take a look a the code to make sure it is efficient in its memory usage.

**Comment by pbalsgaard** [comment]
It created the emfta file, but the error occurred when trying to generate visual representation. I can make the visual representation after increasing the memory allocation. It seems that minimum cutsets couldn't handle the complexity of the model, because the model has 24 error events, but the minimum cutset fault tree has many identical copies of a single branch, with almost 2400 events total.

**Comment by reteprelief** [comment]
I reworked the minimal cut set generation.
Instead of generating the full list of cut sets and then removing unnecessary ones, we now check at the time of addition whether the existing cutsets already cover the candidate to be inserted, and whether the candidate to be inserted covers existing ones and removes them accordingly.
It should address the problem of "many identical copies of a single branch". 
The update is available in the testing (nightly build) as well as the latest stable release 2.2.2.
