### ISSUE TITLE
check for package usage

### ISSUE THREAD

**Issue by juli1** [osate/ErrorModelV2#50]
When referencing an error type/state machine, the EMV2 tool should check that the package is included and not look into the whole/complete workspace.

**Comment by reteprelief** [comment]
From the standard: The qualifying package of an Error Behavior State Machine reference does not have to be listed in the with clause of the package containing the classifier with the Error Model subclause.

The idea was that we do not have to add items to the with clause in the core model because an annex has a dependency on another package.
