### ISSUE TITLE
Cannot apply property to error propagation

### ISSUE THREAD

**Issue by joeseibel** [osate/ErrorModelV2#80]
Should this be legal?
```
package pkg
public
	with EMV2;
	
	abstract a
	annex EMV2 {**
		use types ErrorLibrary;
		
		error propagations
			memory: not out propagation {AboveRange};
		end propagations;
		
		properties
			--Error Message: mismatched input 'memory' expecting RULE_ID
			EMV2::hazards => () applies to memory;
	**};
	end a;
end pkg;
```

**Comment by reteprelief** [comment]
Joe,
Oops.
This should be legal. The problem is that for defining the propagation we use the keywords ‘memory’ etc. while the containment path only expects identifiers.

Two possible fixes:
Option 1: In the containment path escape “memory”  as “^memory” which Xtext treats as identifier “memory”. We then have to fix the EMV2LinkingService to find the error propagations for those IDs .
Option 2: remove PropagationKind (keywords ‘memory’ etc. ) as rule. The linkingservice lookup should pick up the propagations.

Peter

**Comment by lwrage** [comment]
There's a deeper issue: error propagations aren't really named elements in the sense that they have a name that identifies a unique element. This goes against the concept of named elements in the core language where names are unique in a namespace. If the standard remains as it is, should a property then apply to all propagations with the same name (`in`, `out`, `not in`, `not out`)?

**Comment by reteprelief** [comment]
Lutz, you are right. I struggled with this. On one hand an explicit identifier leads to users having to come up with names that are effectively the same as those of the feature.
On the other hand one can look at the propagation declaration as associating an error type with a feature in the core model.

**Comment by reteprelief** [comment]
containment paths now support referencing binding points. 
The implementation uses the new path mechanism that separates the core path from the EMV2 subpath by @ as documented in the EMV2 Annex.
